# This is a basic workflow to help you get started with Actions

name: Call Custom action

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job11:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        id: code-checout
        uses: actions/checkout@v2
        
      - name: Custom action from another repo
        id: custom-github-action-repo-main
        uses: shibunair77/GitHubActions@main
  job12:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: job11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      - name: Custom action from same repo
        id: custom-github-action-same-repo
        uses: "./.github/actions/greeting"
        with:
          who-to-greet: 'Shibu'

   
